### PR TITLE
fixed some typos

### PR DESCRIPTION
**Pull request by SinithH**
fixed some typos

### CODE REVIEW

**Comment by berkus** [comment]
Hi, thanks for this fix, but can you please check why it contains two commits with the same change?

**Comment by SinithH** [comment]
because I have merged it into my forked repo first

**Comment by berkus** [comment]
Ok, we generally use rebase instead of self-merges, could you please rebase your PR to the latest master?

**Comment by SinithH** [comment]
How can I do that?

**Comment by berkus** [comment]
If you use gitup from gitup.co you just press opt+r on the branch your want to rebase and then force push it.

You could also 
1. make a new local branch with the same name but starting from current master; 
2. cherry pick commit [919bf84] into it, and
3. force push it over your old branch (something like `git push --fore origin SinithH-patch-1`). This will update the PR automatically.

**Comment by SinithH** [comment]
I have no idea how to do that
I am new to these

**Comment by berkus** [comment]
Hacktoberfest is a good time to learn :)

https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

**Comment by berkus** [comment]
It would make sense to just start over from the current master (it has been updated just a few mins ago).

**Comment by SinithH** [comment]
I can't understand

**Pull request merged**
